name: ilgrigio-reserveringen
region: ams

alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED

envs:
    - key: APP_ENV
      value: prod
      scope: RUN_AND_BUILD_TIME
    - key: APP_SECRET
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: APP_NAME
      value: "Il Grigio Reserveringen"
      scope: RUN_AND_BUILD_TIME
    - key: MAILER_DSN
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: MAILER_FROM_EMAIL
      value: ses@ilgrigio.nl
      scope: RUN_AND_BUILD_TIME
    - key: MAILER_FROM_NAME
      value: "Il Grigio Reserveringen"
      scope: RUN_AND_BUILD_TIME
    - key: ADMIN_EMAIL
      value: reserveringen@ilgrigio.nl
      scope: RUN_AND_BUILD_TIME
    - key: WOOCOMMERCE_CONSUMER_KEY
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: WOOCOMMERCE_CONSUMER_SECRET
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: WOOCOMMERCE_WEBHOOK_SECRET
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: ILGRIGIO_BASE_URL
      value: https://backoffice.ilgrigio.nl
      scope: RUN_AND_BUILD_TIME
    - key: ILGRIGIO_BASE_API_URL
      value: https://backoffice.ilgrigio.nl/wp-json
      scope: RUN_AND_BUILD_TIME
    - key: ILGRIGIO_RESERVERINGEN_BASE_URL
      value: https://reserveringen.ilgrigio.nl
      scope: RUN_AND_BUILD_TIME
    - key: PDF_TOKEN_SECRET
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: PDF_TOKEN_EXPIRATION_DAYS
      value: "150"
      scope: RUN_AND_BUILD_TIME
    - key: ILGRIGIO_TICKET_API_URL
      value: https://backoffice.ilgrigio.nl/wp-json/tc-custom-endpoint/order/get
      scope: RUN_AND_BUILD_TIME
    - key: ILGRIGIO_TICKET_API_KEY
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: MOLLIE_API_KEY
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: MAX_TICKETS_PER_ORDER
      value: "25"
      scope: RUN_AND_BUILD_TIME
    - key: TAX_RATE
      value: "9"
      scope: RUN_AND_BUILD_TIME
    - key: API_KEY
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: CORS_ALLOW_ORIGIN
      value: ^https://kassa\.ilgrigio\.nl$
      scope: RUN_AND_BUILD_TIME
    - key: SECURE_CHANNEL
      value: https
      scope: RUN_AND_BUILD_TIME
    - key: MESSENGER_TRANSPORT_DSN
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: NEW_RELIC_LICENSE_KEY
      scope: RUN_AND_BUILD_TIME
      type: SECRET
    - key: NEW_RELIC_LOGS_ENDPOINT
      value: https://log-api.eu.newrelic.com
      scope: RUN_AND_BUILD_TIME

services:
    - name: web
      github:
          repo: mikerovers/ilgrigio-reserveringen-backoffice
          branch: master
          deploy_on_push: true
      dockerfile_path: Dockerfile.web
      instance_size_slug: basic-xxs
      instance_count: 1
      http_port: 8080
      alerts:
          - rule: RESTART_COUNT
            operator: GREATER_THAN
            value: 3
            window: FIVE_MINUTES
          - rule: CPU_UTILIZATION
            operator: GREATER_THAN
            value: 80
            window: FIVE_MINUTES
          - rule: MEM_UTILIZATION
            operator: GREATER_THAN
            value: 80
            window: FIVE_MINUTES
      envs:
          - key: NEW_RELIC_APP_NAME
            value: ilgrigio-reserveringen-web
            scope: RUN_AND_BUILD_TIME

workers:
    - name: messenger-consumer
      github:
          repo: mikerovers/ilgrigio-reserveringen-backoffice
          branch: master
          deploy_on_push: true
      dockerfile_path: Dockerfile
      instance_size_slug: basic-xxs
      instance_count: 1
      alerts:
          - rule: RESTART_COUNT
            operator: GREATER_THAN
            value: 3
            window: FIVE_MINUTES
          - rule: CPU_UTILIZATION
            operator: GREATER_THAN
            value: 80
            window: FIVE_MINUTES
          - rule: MEM_UTILIZATION
            operator: GREATER_THAN
            value: 80
            window: FIVE_MINUTES
      envs:
          - key: NEW_RELIC_APP_NAME
            value: ilgrigio-reserveringen-worker
            scope: RUN_AND_BUILD_TIME

domains:
    - domain: reserveringen.ilgrigio.nl
      type: PRIMARY
    - domain: www.reserveringen.ilgrigio.nl
      type: ALIAS

ingress:
    rules:
        - match:
              path:
                  prefix: /
          component:
              name: web
